name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        
    - name: Publish
      run: dotnet publish BlazorWebAssemblyTest/BlazorWebAssemblyTest.csproj -c Release -o release --nologo
      
    - name: Change base-tag in index.html from / to the necessary
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorWebAssemblyTest\/" \/>/g' ./BlazorWebAssemblyTest/bin/release/net6.0/publish/wwwroot/index.html
      
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
      
    - name: Add .nojekyll file
      run: touch ./BlazorWebAssemblyTest/bin/release/net6.0/publish/wwwroot/.nojekyll
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: deploy publish
      with:
        branch: deploy
        folder: ./BlazorWebAssemblyTest/bin/release/net6.0/publish/wwwroot
